
name: global_asset_bm

base_weight:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.05
  - 0.04
  - 0.01
  - 0.5

wgt_range_min:
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.3

wgt_range_max:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.2
  - 0.2
  - 0.1
  - 0.7

mdd_cp: 0.1
lr: 0.02

excluded_asset_idx:
  - 6
