data:
  name: app

  _target_: v3_latest.dataset.DataManager

  cash_idx: 3
  num_assets: 4

  data_path:
    asset: ./data/app_data_${data.update}.txt
    macro: ./data/macro_data_${data.update}.txt


